version: '3.8'
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --fork-url https://opbnb-testnet.infura.io/v3/aad532756b6e44b6a10d9922a151240e --port 8545 --chain-id 31337 --auto-impersonate
    ports:
      - "8545:8545"
    environment:
      - ANVIL_RPC=http://anvil:8545
      - CHAIN_ID=31337
  cex:
    build:
      context: ../cex
      dockerfile: Dockerfile
    image: mock-cex:latest
    container_name: mock-cex
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ticker"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - ANVIL_RPC=https://opbnb-testnet.infura.io/v3/aad532756b6e44b6a10d9922a151240e
      - CHAIN_ID=31337
  dex:
    build: ../dex
    ports:
      - "9000:9000"
    environment:
      - ANVIL_RPC=https://opbnb-testnet.infura.io/v3/aad532756b6e44b6a10d9922a151240e
      - CHAIN_ID=31337
  dashboard:
    build: ../dashboard
    ports:
      - "8050:8050"
    environment:
      - ANVIL_RPC=https://opbnb-testnet.infura.io/v3/aad532756b6e44b6a10d9922a151240e
      - CHAIN_ID=31337
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
