services:
  dex:
    build: ../dex
    ports:
      - "9000:9000"
    environment:
      - CHAIN_ID=${CHAIN_ID}
    entrypoint: []
    command: ["anvil", "--host", "0.0.0.0", "--port", "9000", "--chain-id", "12345"]
  cex:
    build: ../cex
    ports:
      - "8000:8000"
    environment:
      - CEX_API_PORT=${CEX_API_PORT}
      - CEX_API_KEY=${CEX_API_KEY}
      - CEX_API_SECRET=${CEX_API_SECRET}
      - CEX_DB_PATH=${CEX_DB_PATH}
      - CHAIN_ID=${CHAIN_ID}
  dashboard:
    build: ../dashboard
    ports:
      - "8501:8501"
    environment:
      - DASHBOARD_PORT=${DASHBOARD_PORT}
      - CHAIN_ID=${CHAIN_ID}
    depends_on:
      - dex
      - cex
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
